# default
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
text: "my best friend"
---
# dev
spring:
  config:
    activate:
      on-profile: dev