# default
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
---
# dev
spring:
  config:
    activate:
      on-profile: dev
    import:
      - classpath:application-dev.yml