# default
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
text: "my best friend"
logging:
  level:
    root: WARN
    com.nemuki.cypherhelloworld.controller.HelloWorld: TRACE
---
# dev
spring:
  config:
    activate:
      on-profile: dev